Repository CatalaLang/catala, pull requests merged in 2021-05, with the labels that each got.

#111 Remove parser tokens for builtin functions
  CONTRIBUTING.md
  src/catala/surface/ast.ml
  src/catala/surface/ast.mli
  src/catala/surface/dune
  src/catala/surface/lexer.ml
  src/catala/surface/lexer.mli
  src/catala/surface/lexer_common.ml
  src/catala/surface/lexer_common.mli
  src/catala/surface/lexer_en.ml
  src/catala/surface/lexer_en.mli
  src/catala/surface/lexer_fr.ml
  src/catala/surface/lexer_fr.mli
  src/catala/surface/parser.messages
  src/catala/surface/parser.mly
  src/catala/surface/parser_driver.ml
  src/catala/surface/tokens.mly
Labels: ✨ enhancement, 🔧 compiler

#121 feat(compiler): allow to use the grave accent character outside code blocks and add language inference from file extension
  src/catala/driver.ml
  src/catala/surface/lexer.ml
  src/catala/surface/lexer_en.ml
  src/catala/surface/lexer_fr.ml
  src/catala/surface/lexer_pl.ml
  src/catala/surface/parser_driver.ml
  tests/Makefile
  tests/test_literate/good/output/test_grave_char.catala.A.out
  tests/test_literate/good/output/test_grave_char.catala_en.A.out
  tests/test_literate/good/output/test_grave_char.catala_fr.A.out
  tests/test_literate/good/output/test_grave_char.catala_pl.A.out
  tests/test_literate/good/test_grave_char.catala
  tests/test_literate/good/test_grave_char.catala_en
  tests/test_literate/good/test_grave_char.catala_fr
  tests/test_literate/good/test_grave_char.catala_pl
Labels: ✨ enhancement, 🔧 compiler

#126 fix(compiler): correct the handling of the Division_by_zero exception
  src/catala/dcalc/interpreter.ml
  tests/Makefile
  tests/test_arithmetic/bad/division_by_zero.catala_en
  tests/test_arithmetic/bad/output/division_by_zero.catala_en.Dec.out
  tests/test_arithmetic/bad/output/division_by_zero.catala_en.Int.out
  tests/test_arithmetic/bad/output/division_by_zero.catala_en.Money.out
  tests/test_date/bad/output/uncomparable_duration.catala_en.Ge.out
  tests/test_date/bad/output/uncomparable_duration.catala_en.Gt.out
  tests/test_date/bad/output/uncomparable_duration.catala_en.Le.out
  tests/test_date/bad/output/uncomparable_duration.catala_en.Lt.out
  tests/test_date/bad/uncomparable_duration.catala_en
Labels: ❌ bug, 🏗️ build system, 🔧 compiler

#127 feat(compiler): add the duration division operator
  doc/syntax/Makefile
  doc/syntax/syntax.pdf
  doc/syntax/syntax.tex
  src/catala/dcalc/interpreter.ml
  src/catala/dcalc/typing.ml
  src/catala/runtime.ml
  src/catala/runtime.mli
  src/catala/surface/lexer_en.ml
  src/catala/surface/lexer_fr.ml
  src/catala/surface/lexer_pl.ml
  src/catala/surface/parser.messages
  src/catala/surface/parser.mly
  src/catala/surface/tokens.mly
  tests/Makefile
  tests/test_arithmetic/bad/division_by_zero.catala_en
  tests/test_arithmetic/bad/output/division_by_zero.catala_en.Duration.out
  tests/test_date/bad/indivisable_durations.catala_en
  tests/test_date/bad/output/indivisable_durations.catala_en.DayByMonth.out
  tests/test_date/good/durations.catala_en
  tests/test_date/good/output/durations.catala_en.A.out
Labels: ✨ enhancement, 📘 documentation, 🔧 compiler
