Repository CatalaLang/catala, pull requests merged in 2021-06, with the labels that each got.

#128 feat(syntax_highlighting): add vim syntax files
  examples/polish_taxes/tests/test_a7_u1_p1.catala_pl
  examples/polish_taxes/tests/test_a7_u1_p2.catala_pl
  syntax_highlighting/en/ace/mode-catala_en.js
  syntax_highlighting/en/atom/grammars/catala_en.cson
  syntax_highlighting/en/catala_en.iro
  syntax_highlighting/en/pygments/catala_en_lexer/lexer.py
  syntax_highlighting/en/vim/catala_en.vim
  syntax_highlighting/en/vscode/syntaxes/catalavs.xml
  syntax_highlighting/fr/ace/mode-catala_fr.js
  syntax_highlighting/fr/atom/grammars/catala_fr.cson
  syntax_highlighting/fr/catala_fr.iro
  syntax_highlighting/fr/pygments/catala_fr_lexer/lexer.py
  syntax_highlighting/fr/vim/catala_fr.vim
  syntax_highlighting/fr/vscode/syntaxes/catalavs.xml
  syntax_highlighting/pl/atom/grammars/catala_pl.cson
  syntax_highlighting/pl/catala_pl.iro
  syntax_highlighting/pl/pygments/catala_pl_lexer/lexer.py
  syntax_highlighting/pl/vim/catala_pl.vim
Labels: ✨ enhancement

#129 feat(compiler)!: add wildcard in patterns
  CONTRIBUTING.md
  src/catala/surface/ast.ml
  src/catala/surface/desugaring.ml
  src/catala/surface/lexer_en.ml
  src/catala/surface/lexer_fr.ml
  src/catala/surface/lexer_pl.ml
  src/catala/surface/parser.messages
  src/catala/surface/parser.mly
  src/catala/surface/tokens.mly
  syntax_highlighting/en/ace/mode-catala_en.js
  syntax_highlighting/en/atom/grammars/catala_en.cson
  syntax_highlighting/en/pygments/catala_en_lexer/lexer.py
  syntax_highlighting/en/vim/catala_en.vim
  syntax_highlighting/en/vscode/syntaxes/catalavs.xml
  syntax_highlighting/fr/ace/mode-catala_fr.js
  syntax_highlighting/fr/atom/grammars/catala_fr.cson
  syntax_highlighting/fr/pygments/catala_fr_lexer/lexer.py
  syntax_highlighting/fr/vim/catala_fr.vim
  syntax_highlighting/fr/vscode/syntaxes/catalavs.xml
  syntax_highlighting/pl/atom/grammars/catala_pl.cson
  syntax_highlighting/pl/pygments/catala_pl_lexer/lexer.py
  syntax_highlighting/pl/vim/catala_pl.vim
  tests/test_enum/bad/ambiguous_wildcard.catala_en
  tests/test_enum/bad/not_ending_wildcard.catala_en
  tests/test_enum/bad/output/ambiguous_wildcard.catala_en.A.out
  tests/test_enum/bad/output/not_ending_wildcard.catala_en.First_case.out
  tests/test_enum/bad/output/not_ending_wildcard.catala_en.Middle_case.out
  tests/test_enum/bad/output/useless_wildcard.catala_en.A.out
  tests/test_enum/bad/useless_wildcard.catala_en
  tests/test_enum/good/output/wildcard.catala_en.Simple_case.out
  tests/test_enum/good/output/wildcard.catala_en.Simple_case_2.out
  tests/test_enum/good/wildcard.catala_en
  tests/test_literate/good/test_grave_char.catala_fr
Labels: ✨ enhancement, 💡 language, 🔧 compiler

#131 Fix #118: remove code block delimiters in generated HTML files
  examples/tutoriel_fr/Makefile
  src/catala/literate/html.ml
Labels: ❓ invalid, 🔧 compiler

#132 Feat #115: annotate NoValueProvided exn with location informations
  .gitattributes
  examples/Makefile.common.mk
  french_law_js/french_law.js
  src/catala/lcalc/print.ml
  src/catala/lcalc/to_ocaml.ml
  src/catala/runtime.ml
  src/catala/runtime.mli
  src/french_law/bench.ml
  src/french_law/law_source/allocations_familiales.ml
Labels: ✨ enhancement, 🔧 compiler

#135 Python backend
  .gitattributes
  .github/workflows/build.yml
  .gitignore
  CONTRIBUTING.md
  Makefile
  README.md
  compiler/driver.ml
  compiler/dune
  compiler/lcalc/ast.ml
  compiler/lcalc/ast.mli
  compiler/lcalc/backends.ml
  compiler/lcalc/backends.mli
  compiler/lcalc/compile_with_exceptions.ml
  compiler/lcalc/lcalc.mld
  compiler/lcalc/to_ocaml.ml
  compiler/scalc/ast.ml
  compiler/scalc/compile_from_lambda.ml
  compiler/scalc/dune
  compiler/scalc/scalc.mld
  compiler/scalc/to_python.ml
  compiler/scalc/to_python.mli
  compiler/utils/cli.ml
  compiler/utils/cli.mli
  examples/Makefile.common.mk
  examples/allocations_familiales/.gitignore
  examples/allocations_familiales/tests/tests_allocations_familiales.catala_fr
  french_law/README.md
  french_law/js/README.md
  french_law/ocaml/README.md
  french_law/ocaml/law_source/unit_tests/run_tests.ml
  french_law/python/.gitignore
  french_law/python/Makefile
  french_law/python/README.md
  french_law/python/dependencies.txt
  french_law/python/main.py
  french_law/python/setup_env.sh
  french_law/python/src/__init__.py
  french_law/python/src/allocations_familiales.py
  french_law/python/src/catala.py
Labels: ✨ enhancement, 🔧 compiler
