Repository CatalaLang/catala, pull requests merged in 2022-09, with the labels that each got.

#325 NSW community gaming examples
  .gitignore
  examples/NSW_community_gaming/.gitignore
  examples/NSW_community_gaming/Makefile
  examples/NSW_community_gaming/nsw_art_union.catala_en
  examples/NSW_community_gaming/nsw_charity_housie.catala_en
  examples/NSW_community_gaming/nsw_club_bingo.catala_en
  examples/NSW_community_gaming/nsw_draw_lottery.catala_en
  examples/NSW_community_gaming/nsw_no_draw_lottery.catala_en
  examples/NSW_community_gaming/nsw_progressive_lottery.catala_en
  examples/NSW_community_gaming/nsw_social_housie.catala_en
  examples/NSW_community_gaming/tests/output/test_nsw_art_union.catala_en.Test1.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_art_union.catala_en.Test2.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_art_union.catala_en.Test3.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_art_union.catala_en.Test4.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_charity_housie.catala_en.Test1.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_charity_housie.catala_en.Test2.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_charity_housie.catala_en.Test3.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_charity_housie.catala_en.Test4.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_club_bingo.catala_en.Test1.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_club_bingo.catala_en.Test2.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_club_bingo.catala_en.Test3.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_club_bingo.catala_en.Test4.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_club_bingo.catala_en.Test5.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_draw_lottery.catala_en.Test1.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_draw_lottery.catala_en.Test2.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_draw_lottery.catala_en.Test3.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_draw_lottery.catala_en.Test4.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_no_draw_lottery.catala_en.Test1.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_no_draw_lottery.catala_en.Test2.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_no_draw_lottery.catala_en.Test3.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_no_draw_lottery.catala_en.Test4.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_progressive_lottery.catala_en.Test1.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_progressive_lottery.catala_en.Test2.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_progressive_lottery.catala_en.Test3.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_progressive_lottery.catala_en.Test4.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_social_housie.catala_en.Test1.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_social_housie.catala_en.Test2.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_social_housie.catala_en.Test3.Interpret
  examples/NSW_community_gaming/tests/output/test_nsw_social_housie.catala_en.Test4.Interpret
  examples/NSW_community_gaming/tests/test_nsw_art_union.catala_en
  examples/NSW_community_gaming/tests/test_nsw_charity_housie.catala_en
  examples/NSW_community_gaming/tests/test_nsw_club_bingo.catala_en
  examples/NSW_community_gaming/tests/test_nsw_draw_lottery.catala_en
  examples/NSW_community_gaming/tests/test_nsw_no_draw_lottery.catala_en
  examples/NSW_community_gaming/tests/test_nsw_progressive_lottery.catala_en
  examples/NSW_community_gaming/tests/test_nsw_social_housie.catala_en
Labels: ⚖️ program

#327 Fix nix build
  .nix/catala.nix
  .nix/clerk.nix
  .nix/ninja_utils.nix
  .nix/packages.nix
  .nix/ubase.nix
  flake.lock
Labels: ❌ bug, 🏗️ build system

#306 Use `dates_calc` library
  .nix/catala.nix
  Dockerfile
  catala.opam
  compiler/dcalc/interpreter.ml
  compiler/dcalc/typing.ml
  compiler/surface/dune
  compiler/surface/lexer.cppo.ml
  compiler/surface/parser.messages
  compiler/surface/parser.mly
  compiler/surface/tokens.mly
  compiler/verification/dune
  compiler/verification/z3backend.real.ml
  doc/syntax/syntax.pdf
  doc/syntax/syntax.tex
  dune-project
  runtimes/ocaml/dune
  runtimes/ocaml/runtime.ml
  runtimes/ocaml/runtime.mli
  syntax_highlighting/emacs/catala-mode.el
  syntax_highlighting/en/catala_en.iro
  syntax_highlighting/en/vim/catala_en.vim
  syntax_highlighting/en/vscode/syntaxes/catalavs.xml
  syntax_highlighting/fr/catala_fr.iro
  syntax_highlighting/fr/vim/catala_fr.vim
  syntax_highlighting/fr/vscode/syntaxes/catalavs.xml
  syntax_highlighting/pl/catala_pl.iro
  syntax_highlighting/pl/vim/catala_pl.vim
  tests/test_arithmetic/bad/division_by_zero.catala_en
  tests/test_arithmetic/bad/output/division_by_zero.catala_en.Duration.Interpret
  tests/test_date/bad/indivisable_durations.catala_en
  tests/test_date/bad/output/indivisable_durations.catala_en.DayByMonth.Interpret
  tests/test_date/good/durations.catala_en
  tests/test_date/good/output/durations.catala_en.A.Interpret
  tests/test_date/good/output/simple.catala_en.A.Interpret
Labels: ✨ enhancement, 🔧 compiler, 🔚 backends

#331 Better Z3 encoding of EMatch nodes
  compiler/verification/z3backend.real.ml
Labels: ✅ proof

#333 Do not hardfail when pretty-printing unknown Z3 variables
  compiler/verification/z3backend.real.ml
  tests/test_proof/bad/enums-nonbool-empty.catala_en
  tests/test_proof/bad/enums-nonbool-overlap.catala_en
  tests/test_proof/bad/output/enums-nonbool-empty.catala_en.Proof
  tests/test_proof/bad/output/enums-nonbool-overlap.catala_en.Proof
  tests/test_proof/good/enums-nonbool.catala_en
  tests/test_proof/good/output/enums-nonbool.catala_en.Proof
Labels: ✅ proof

#329 LégiFrance<->Catala connector
  Makefile
  catala_legifrance.opam
  compiler/surface/ast.ml
  compiler/surface/lexer_common.ml
  compiler/surface/parser.mly
  compiler/surface/tokens.mly
  examples/aides_logement/archives.catala_fr
  examples/aides_logement/arrete_2019-09-27.catala_fr
  examples/aides_logement/autres_sources.catala_fr
  examples/aides_logement/code_construction_legislatif.catala_fr
  examples/aides_logement/code_construction_reglementaire.catala_fr
  examples/aides_logement/code_sécurité_sociale.catala_fr
  examples/prestations_familiales/sécurité_sociale_L.catala_fr
  examples/smic/smic.catala_fr
  french_law/catala_legifrance/api.ml
  french_law/catala_legifrance/api.mli
  french_law/catala_legifrance/catala_legifrance.ml
  french_law/catala_legifrance/cli.ml
  french_law/catala_legifrance/date.ml
  french_law/catala_legifrance/diff.ml
  french_law/catala_legifrance/diff.mli
  french_law/catala_legifrance/dune
  french_law/js/french_law.js
  french_law/ocaml/law_source/aides_logement.ml
  french_law/python/src/aides_logement.py
Labels: ✨ enhancement, 🏗️ build system
