Repository CatalaLang/catala, pull requests merged in 2023-09, with the labels that each got.

#503 bugfix: address breaking change in markdown-mode v2.6
  syntax_highlighting/emacs/catala-mode.el
Labels: ❌ bug

#509 Remove catala_legifrance
  .github/workflows/run-make-all.yml
  Makefile
  README.md
  catala_legifrance.opam
  dune
  french_law/catala_legifrance/api.ml
  french_law/catala_legifrance/api.mli
  french_law/catala_legifrance/catala_legifrance.ml
  french_law/catala_legifrance/date.ml
  french_law/catala_legifrance/diff.ml
  french_law/catala_legifrance/diff.mli
  french_law/catala_legifrance/dune
  french_law/catala_legifrance/legifrance_cli.ml
  generate_website_assets.sh
Labels: ❓ invalid, 🏗️ build system

#499 Improvements to the Polish translation
  compiler/surface/lexer_pl.cppo.ml
  examples/polish_taxes/podatek_od_czynnosci_cywilnoprawnych/rozdzial_3.catala_pl
  examples/polish_taxes/tests/test_a7_u1_p1.catala_pl
  examples/polish_taxes/tests/test_a7_u1_p2.catala_pl
  examples/polish_taxes/tests/test_a7_u1_p3.catala_pl
  examples/polish_taxes/tests/test_a7_u1_p4.catala_pl
  examples/polish_taxes/tests/test_a7_u1_p7.catala_pl
  examples/polish_taxes/tests/test_a7_u1_p9.catala_pl
Labels: ✨ enhancement, 🔧 compiler

#511 Fixes OCaml error not caught in JS
  compiler/plugins/api_web.ml
  french_law/ocaml/api_web.ml
  tests/test_modules/good/.gitignore
Labels: ❓ invalid, 🏗️ build system

#515 Mise à jour du calcul des aides au logement avec la réforme des retraites
  examples/aides_logement/archives.catala_fr
  examples/aides_logement/code_construction_reglementaire.catala_fr
  examples/aides_logement/code_sécurité_sociale.catala_fr
  examples/aides_logement/prologue.catala_fr
Labels: ⚖️ program

#520 Fix linebreaking in LaTeX Catala code
  compiler/literate/latex.ml
Labels: ❌ bug, 🏗️ build system

#518 Improve assertion failure message
  compiler/dcalc/from_scopelang.ml
  compiler/desugared/ast.ml
  compiler/desugared/ast.mli
  compiler/desugared/from_surface.ml
  compiler/lcalc/closure_conversion.ml
  compiler/lcalc/compile_without_exceptions.ml
  compiler/plugins/explain.ml
  compiler/plugins/lazy_interp.ml
  compiler/scopelang/ast.ml
  compiler/scopelang/ast.mli
  compiler/scopelang/from_desugared.ml
  compiler/shared_ast/definitions.ml
  compiler/shared_ast/interpreter.ml
  compiler/shared_ast/interpreter.mli
  compiler/shared_ast/optimizations.ml
  compiler/shared_ast/program.ml
  compiler/shared_ast/typing.ml
  compiler/surface/ast.ml
  compiler/surface/parser_driver.ml
Labels: ✨ enhancement, 🔧 compiler
