Repository CatalaLang/catala, pull requests merged in 2023-01, with the labels that each got.

#369 Updates the specified repo for pandoc
  Dockerfile
Labels: ❓ invalid, 🏗️ build system

#376 Fix man page generation for the website
  Makefile
  dune
  french_law/catala_legifrance/catala_legifrance.ml
  french_law/catala_legifrance/legifrance_cli.ml
  french_law/js/french_law.js
  generate_website_assets.sh
  syntax_highlighting/en/atom/package.json
  syntax_highlighting/fr/atom/package.json
  syntax_highlighting/pl/atom/package.json
Labels: 📘 documentation, ❓ invalid

#388 Actually merging #353
  compiler/verification/conditions.ml
  compiler/verification/conditions.mli
  compiler/verification/io.ml
  compiler/verification/io.mli
  compiler/verification/solver.ml
  compiler/verification/z3backend.dummy.ml
  compiler/verification/z3backend.real.ml
  tests/test_proof/bad/assert-empty.catala_en
  tests/test_proof/good/assert.catala_en
Labels: ❓ invalid
